services:
#    gcd.example:
#        class: GCDBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  redirect.after.login:
    class: GCDBundle\Redirection\AfterLoginRedirection
    arguments: [@router]
 